repos:
  - repo: local 
    hooks:
      - id: black
        name: black
        entry: black .
        language: python
        exclude: '.pre-commit-config.yaml' 
      - id: isort
        name: isort
        entry: isort .
        language: python
